export const HEADER_HEIGHT = 50;
export const PRIMARY_HEADER_HEIGHT = 40;
export const NAVBAR_WIDTH = 40;
export const APP_MIN_WIDTH = 650;
export const LOGS_PRIMARY_TOOLBAR_HEIGHT = 90;
export const LOGS_SECONDARY_TOOLBAR_HEIGHT = 68;
export const STREAM_PRIMARY_TOOLBAR_HEIGHT = 68;
export const STREAM_SECONDARY_TOOLBAR_HRIGHT = 90;